Make `PEMDocument` `Hashable`
apple/swift-asn1 pull request #28
Opened 2023-04-20 16:33 UTC by dnadoba

2023-04-20 19:08 UTC, Lukasa approved these changes

2023-04-20 19:08 UTC, Lukasa requested changes
Actually, wanna add Sendable too?

2023-04-20 20:04 UTC, dnadoba commented
Good idea, added.

2023-04-21 09:36 UTC, Lukasa approved these changes

2023-04-21 09:36 UTC, merged